apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower-app-deployment
spec: # It define the behavior of the Deployment
  replicas: 2
  selector:
    matchLabels:
      app: web
  template: # It defines the Pod Definiation
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: flower-contianer
        image: rengaraj12345/sre-test-image:1.0
        resources:
          limits:
            memory: "500Mi"
            cpu: "300m"
          requests:
            memory: "128Mi"
            cpu: "200m"  
        ports:
        - containerPort: 3015
---
apiVersion: apps/v1
kind: Service
metadata:
  name: flower-app-svc
spec:
  selector:
    app: web
  ports:
  - port: 3017 # Service Port Number on which port number you want to access the application
    targetPort: 3015 # on which Port Number your application is running
    Protocol: TCP
  type: LoadBalancer
